stages:
  - lint
  - test

image: python:3.10-slim

before_script:
  - pip install --no-cache-dir -r requirements.txt

linting:
  stage: lint
  script:
    - isort . --check-only
    - black . --check
    - flake8 .
    - mypy .

unit_tests:
  stage: test
  script:
    - pytest